export enum EMealCategory {
  VEGAN = "vegan",
  VEGETARIAN = "vegetarian",
  HALAL = "halal",
  ITALIAN = "italian",
  ASIAN = "asian",
  CHINESE = "chinese",
  RAW = "raw",
  DESSERT = "dessert",
  SWEETS = "sweets",
  PASTA = "pasta",
  GERMAN = "german",
  KOREAN = "korean",
  SUSHI = "sushi",
  "BAKEDGOODS" = "baked goods",
}
