export enum EMealReservationState {
  PENDING = "PENDING",
  SELLER_ACCEPTED = "SELLER_ACCEPTED",
  SELLER_REJECTED = "SELLER_REJECTED",
  BUYER_CONFIRMED = "BUYER_CONFIRMED",
  BUYER_REJECTED = "BUYER_CANCELLED",
}
